language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

osx_image: xcode61

#HACK Install these packages when ubuntu vms are updated libavformat-dev libavdevice-dev libavcodec-dev libavutil-dev

before_install:
  - if [[ $CXX == g++ ]]; then sudo add-apt-repository -y ppa:boost-latest/ppa && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libboost1.55-all-dev libxml2-dev libmagick++-dev libcdparanoia-dev libssl-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install boost; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

after_success:
  - echo "Add Automated Unit Test!!!"